---
tenants:
  - name: MY_FABRIC
    vrfs:
      - name: default
        svis:
          - id: 30
            name: 'Thirty'
            tags: [ "DB" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.30.30.1
            nodes:
              - node: s2-spine1
                ip_address: 10.30.30.2/24
              - node: s2-spine2
                ip_address: 10.30.30.3/24
          - id: 40
            name: 'Forty'
            tags: [ "DMZ" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.40.40.1
            nodes:
              - node: s2-spine1
                ip_address: 10.40.40.2/24
              - node: s2-spine2
                ip_address: 10.40.40.3/24
          #- id: 55
          #  name: 'Fityfive'
          #  tags: [ "DMZ" ]
          #  enabled: true
          #  ip_virtual_router_addresses:
          #    - 10.55.55.1
          #  nodes:
          #    - node: s2-spine1
          #      ip_address: 10.55.55.2/24
          #    - node: s2-spine2
          #      ip_address: 10.55.55.3/24
